host:
  ip: 192.168.5.7

spring:
  datasource:
    druid:
      url: jdbc:mysql://${host.ip}:3306/bmr_config?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  redis:
    host: ${host.ip}
    port: 6379
    password:
    database: 1
    connect-timeout: 3000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ant.bmr.config.data.metadata

minio:
  endpoint: http://${host.ip}:9000
  accessKey: minioadmin
  secretKey: minioadmin

redisson:
  address: redis://${host.ip}:6379

