server:
  port: 4643
spring:
  profiles:
    active: uat
  application:
    name: bmr-config-server
  servlet:
    multipart:
      max-request-size: 20GB
      max-file-size: 20GB

logging:
  level:
    root: info