host:
  ip: 127.0.0.1

spring:
  datasource:
    druid:
      url: jdbc:mysql://${host.ip}:3306/bmr_config?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
  redis:
    host: ${host.ip}
    port: 6379
    password:
    database: 0
    connect-timeout: 3000
  #链路追踪
  sleuth:
    sampler:
      probability: 1.0
    redis:
      enabled: false
  zipkin:
    base-url: http://${host.ip}:9411
    sender:
      type: web
    discovery-client-enabled: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ant.bmr.config.data.metadata

minio:
  endpoint: http://${host.ip}:9000
  accessKey: minioadmin
  secretKey: minioadmin

redisson:
  address: redis://${host.ip}:6379

