spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bmr_config?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    connect-timeout: 3000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ant.bmr.config.data.metadata

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin


